---

- hosts: all
  roles:
    - role: ansible-role-nginx-proxy
      nginx_proxy_direct_locations:
        - location: /direct
          redirect301: /redirect
        - location: /redirect/
          redirect302: /default
        - location: "^~ /default"
          alias: /usr/share/nginx/html
      nginx_proxy_redirect_map:
        - match: default
          dest: /
        - match: /map?search=abc1
          dest: /redirectmap?query=def2
        - match: ~/map
          dest: /redirectmap
      nginx_proxy_redirect_map_locations:
        - location: "~ ^/map($|/)"
          code: 302
