---
# tasks file for roles/nginx-proxy

- name: nginx | main config
  become: yes
  template:
    src: nginx-conf.j2
    dest: /etc/nginx/nginx.conf
  notify:
    - restart nginx

- include: nginx-selinux.yml
  when: selinux_enabled

- include: nginx-cache.yml

- include: nginx-websockets.yml

- include: nginx-redirects.yml

- include: nginx-streams.yml

- include: nginx-proxy-sites.yml

- name: nginx | start service
  become: yes
  service:
    enabled: yes
    name: nginx
    state: started
